animalitos/urls.py
from django.urls import path
from . import views

app_name = 'animalitos'

urlpatterns = [
    path('', views.BaseView.as_view(), name='base'),
    path('inicio/', views.InicioView.as_view(), name='inicio'),
    path('nosotros/', views.NosotrosView.as_view(), name='nosotros'),
    path('tienda/', views.TiendaView.as_view(), name='tienda'),
    path('tienda/subseccion/<int:subseccion_id>/', SubseccionView.as_view(), name='subseccion'),
    path('tienda/detalle/<int:producto_id>/', DetalleProductoView.as_view(), name='detalle_producto'),
    path('contacto/', views.ContactoView.as_view(), name='contacto'),
    path('donaciones/', views.DonacionesView.as_view(), name='donaciones')
    # Define otras rutas aquí...
]

tienda/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from animalitos.views import InicioView, NosotrosView, TiendaView, ContactoView, DonacionesView,LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView, RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView 
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', InicioView.as_view(), name='inicio'),
    path('nosotros/', NosotrosView.as_view(), name='nosotros'),
    path('tienda/', TiendaView.as_view(), name='tienda'),
    path('contacto/', ContactoView.as_view(), name='contacto'),
    path('donaciones/', DonacionesView.as_view(), name='donaciones'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
    
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

animalitos/models.py
from django.db import models
from django.contrib.auth.models import User


class Activation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='animalitos_activation')
    created_at = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=20, unique=True)
    email = models.EmailField(blank=True)
class Subseccion(models.Model):
    nombre = models.CharField(max_length=100)

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    descripcion = models.TextField()
    subseccion = models.ForeignKey(Subseccion, on_delete=models.CASCADE)

animalitos/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.urls import reverse
from django.views import View
from .models import Subseccion, Producto

class TiendaView(View):
    def get(self, request):
        subsecciones = Subseccion.objects.all()
        context = {'subsecciones': subsecciones}
        return render(request, 'animalitos/tienda.html', context)

class SubseccionView(View):
    def get(self, request, subseccion_id):
        subseccion = get_object_or_404(Subseccion, id=subseccion_id)
        productos = subseccion.producto_set.all()
        context = {'subseccion': subseccion, 'productos': productos}
        return render(request, 'animalitos/subseccion.html', context)

class DetalleProductoView(View):
    def get(self, request, producto_id):
        producto = get_object_or_404(Producto, id=producto_id)
        context = {'producto': producto}
        return render(request, 'animalitos/detalle_producto.html', context)

class InicioView(TemplateView):
    template_name = 'inicio.html'

class NosotrosView(TemplateView):
    template_name = 'nosotros.html'

class TiendaView(TemplateView):
    template_name = 'tienda.html'
    
class ContactoView(TemplateView):
    template_name = 'contacto.html'

class DonacionesView(TemplateView):
    template_name = 'donaciones.html'

class Nosotros(View):
    template_name = 'accounts/nosotros.html'

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, authenticate, REDIRECT_FIELD_NAME
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LogoutView as BaseLogoutView, PasswordChangeView as BasePasswordChangeView,
    PasswordResetDoneView as BasePasswordResetDoneView, PasswordResetConfirmView as BasePasswordResetConfirmView,
)
from django.shortcuts import get_object_or_404, redirect
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.utils.http import url_has_allowed_host_and_scheme as is_safe_url
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import View, FormView

from .utils import (
    send_activation_email, send_reset_password_email, send_forgotten_username_email, send_activation_change_email,
)
from .forms import (
    SignInViaUsernameForm, SignInViaEmailForm, SignInViaEmailOrUsernameForm, SignUpForm,
    RestorePasswordForm, RestorePasswordViaEmailOrUsernameForm, RemindUsernameForm,
    ResendActivationCodeForm, ResendActivationCodeViaEmailForm, ChangeProfileForm, ChangeEmailForm,
)
from .models import Activation

DISABLE_USERNAME = True

class GuestOnlyView(View):
    def dispatch(self, request, *args, **kwargs):
        # Redirect to the index page if the user already authenticated
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)

        return super().dispatch(request, *args, **kwargs)


class LogInView(GuestOnlyView, FormView):
    template_name = 'animalitos/base.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME or settings.LOGIN_VIA_EMAIL:
            return SignInViaEmailForm

        if settings.LOGIN_VIA_EMAIL_OR_USERNAME:
            return SignInViaEmailOrUsernameForm

        return SignInViaUsernameForm

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        request = self.request

        # If the test cookie worked, go ahead and delete it since its no longer needed
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()

        # The default Django's "remember me" lifetime is 2 weeks and can be changed by modifying
        # the SESSION_COOKIE_AGE settings' option.
        if settings.USE_REMEMBER_ME:
            if not form.cleaned_data['remember_me']:
                request.session.set_expiry(0)

        login(request, form.user_cache)

        redirect_to = request.POST.get(REDIRECT_FIELD_NAME, request.GET.get(REDIRECT_FIELD_NAME))
        url_is_safe = is_safe_url(redirect_to, allowed_hosts=request.get_host(), require_https=request.is_secure())

        if url_is_safe:
            return redirect(redirect_to)

        return redirect(settings.LOGIN_REDIRECT_URL)


class SignUpView(GuestOnlyView, FormView):
    template_name = 'accounts/sign_up.html'
    form_class = SignUpForm

    def form_valid(self, form):
        request = self.request
        user = form.save(commit=False)

        if settings.DISABLE_USERNAME:
            # Set a temporary username
            user.username = get_random_string()
        else:
            user.username = form.cleaned_data['username']

        if settings.ENABLE_USER_ACTIVATION:
            user.is_active = True

        # Create a user record
        user.save()

        # Change the username to the "user_ID" form
        if settings.DISABLE_USERNAME:
            user.username = f'user_{user.id}'
            user.save()

        if settings.ENABLE_USER_ACTIVATION:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.save()

            send_activation_email(request, user.email, code)

            messages.success(
                request, _('You are signed up. To activate the account, follow the link sent to the mail.'))
        else:
            raw_password = form.cleaned_data['password1']

            user = authenticate(username=user.username, password=raw_password)
            login(request, user)

            messages.success(request, _('¡te has conectado exitosamente!'))

            return redirect(reverse('animalitos:base'))


class ActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(Activation, code=code)

        # Activate profile
        user = act.user
        user.is_active = True
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('You have successfully activated your account!'))

        return redirect('accounts:log_in')


class ResendActivationCodeView(GuestOnlyView, FormView):
    template_name = 'accounts/resend_activation_code.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME:
            return ResendActivationCodeViaEmailForm

        return ResendActivationCodeForm

    def form_valid(self, form):
        user = form.user_cache

        activation = user.activation_set.first()
        activation.delete()

        code = get_random_string(20)

        act = Activation()
        act.code = code
        act.user = user
        act.save()

        send_activation_email(self.request, user.email, code)

        messages.success(self.request, _('A new activation code has been sent to your email address.'))

        return redirect('accounts:resend_activation_code')


class RestorePasswordView(GuestOnlyView, FormView):
    template_name = 'accounts/restore_password.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.RESTORE_PASSWORD_VIA_EMAIL_OR_USERNAME:
            return RestorePasswordViaEmailOrUsernameForm

        return RestorePasswordForm

    def form_valid(self, form):
        user = form.user_cache
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))

        if isinstance(uid, bytes):
            uid = uid.decode()

        send_reset_password_email(self.request, user.email, token, uid)

        return redirect('accounts:restore_password_done')


class ChangeProfileView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_profile.html'
    form_class = ChangeProfileForm

    def get_initial(self):
        user = self.request.user
        initial = super().get_initial()
        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        return initial

    def form_valid(self, form):
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()

        messages.success(self.request, _('Profile data has been successfully updated.'))

        return redirect('accounts:change_profile')


class ChangeEmailView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_email.html'
    form_class = ChangeEmailForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial['email'] = self.request.user.email
        return initial

    def form_valid(self, form):
        user = self.request.user
        email = form.cleaned_data['email']

        if settings.ENABLE_ACTIVATION_AFTER_EMAIL_CHANGE:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.email = email
            act.save()

            send_activation_change_email(self.request, email, code)

            messages.success(self.request, _('To complete the change of email address, click on the link sent to it.'))

animalitos/templates/base.html
{% load static %} {% load bootstrap4 %} {% load i18n %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
  <head>
    <meta charset="utf-8" />

    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta
      name="description"
      content="An example of Django project with basic user functionality."
    />
    <meta name="author" content="Felipe Alvarez" />

    <link rel="icon" href="{% static 'favicon.ico' %}" />
    <head>
        <!-- ... otros elementos en el head ... -->
      
        <!-- Estilos CSS de Fancybox -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" />
      
        <!-- jQuery (asegúrate de incluirlo antes de Fancybox) -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
      
        <!-- JavaScript de Fancybox -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>
      </head>

    <!--==== CSS ====-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"
      type="module"
    ></script>

    <!-- Archivos CSS personalizados -->
    <link href="{% static 'animalitos/css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'animalitos/css/style-I.css' %}" rel="stylesheet" />

    <!--===== Íconos =====-->
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    {% load i18n %}
    <nav class="sidebar close">
      <header>
        <div class="image-text">
          <span class="image">
            <img src="{% static 'animalitos/logo.png' %}" alt="logo">
          </span>

          <div class="text header-text">
            <span class="name">Animalitos</span>
            <span class="profession">Pet Shop</span>
          </div>
        </div>
        <i class="bx bx-chevron-right toggle"></i>
      </header>
      {% if request.user.is_authenticated %} ¡Bienvenido!
      <b>{{ request.user.username }}</b>.
       {% else %} 
       {% trans 'Estás como invitado'%} 
       {% endif %}
      <div class="menu-bar">
        <div class="menu">
          <li class="search-box">
            <i class="bx bx-search icon"></i>
            <input type="text" placeholder="Buscar" />
          </li>
          <ul class="menu-links">
            <li class="nav-link">
              <a href="{% url 'inicio' %}">
                <i class="bx bx-home-alt icon"></i>
                <span class="text nav-text">Inicio</span>
              </a>
            </li>
            <li class="nav-link">
              <a href="{% url 'tienda' %}">
                <i class="bx bx-store icon"></i>
                <span class="text nav-text">Tienda</span>
              </a>
            </li>
            <li class="nav-link">
              <a href="{% url 'donaciones' %}">
                <i class="bx bx-donate-heart icon"></i>
                <span class="text nav-text">Donaciones</span>
              </a>
            </li>
            <li class="nav-link">
              <a href="{% url 'nosotros' %}">
                <i class="bx bx-info-circle icon"></i>
                <span class="text nav-text">Nosotros</span>
              </a>
            </li>
            <li class="nav-link">
              <a href="#">
                <i class="bx bx-envelope icon"></i>
                <span class="text nav-text">Contacto</span>
              </a>
            </li>
            {% if request.user.is_authenticated %} {% if
            request.user.is_superuser %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:login' %}"
                >{% trans 'Django administration' %}</a
              >
            </li>
            {% endif %}

            <li class="nav-link">
              <a href="{% url 'accounts:change_password' %}">
                <i class="bx bxs-key icon"></i>
                <span class="text nav-text">{% trans 'Cambiar Contraseña' %}</span>
              </a>
            </li>
            <li class="nav-link">
              <a href="{% url 'accounts:change_profile' %}">
                <i class="bx bxs-credit-card-front icon"></i>
                <span class="text nav-text">{% trans 'Cambiar Perfil' %}</span>
              </a>
            </li>
            <li class="nav-link">
              <a href="{% url 'accounts:change_email' %}">
                <i class="bx bx-envelope icon"></i>
                <span class="text nav-text">{% trans 'Cambiar Email' %}</span>
              </a>
            </li>
            <li class="nav-link">
              <a href="{% url 'accounts:log_out' %}">
                <i class="bx bxs-user-x icon"></i>
                <span class="text nav-text">{% trans 'Log out' %}</span>
              </a>
            </li>

            {% if not request.user.is_authenticated %}
            <li class="nav-link">
              <a class="nav-link" href="{% url 'accounts:log_in' %}">
                <i class="bx bx-user-circle icon"></i>
                <span class="text nav-text">{% trans 'Log in' %}</span>
              </a>
            </li>
            <li class="nav-link">
              <a href="{% url 'accounts:sign_up' %}">
                <i class="bx bx-user-plus icon"></i>
                <span class="text nav-text">Crear Usuario</span>
              </a>
            </li>
            {% endif %}
          </ul>
        </div>
        <div class="bottom-content">
          <li class="mode">
            <div class="moon-sun">
              <i class="bx bx-moon icon moon"></i>
              <i class="bx bx-sun icon sun"></i>
            </div>
            <span class="mode-text text">Dark Mode</span>

            <div class="toggle-switch">
              <span class="switch"></span>
            </div>
          </li>
        </div>
      </div>
    </nav>

    <div class="container-fluid mt-3">
      {% bootstrap_messages %} {% block content %} No content. {% endblock %}
    </div>

    <!-- Scripts JavaScript -->
    <script src="{% static 'animalitos/vendor/jquery/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'animalitos/vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'animalitos/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'animalitos/js/ie10-viewport-bug-workaround.js' %}"></script>
    <script src="{% static 'animalitos/js/script.js' %}"></script>
  </body>
</html>

animalitos/templates/contacto.html
<!-- contacto.html -->
{% extends 'base.html' %}

{% block content %}
<!-- Agrega aquí el menú y los productos de la tienda -->
{% endblock %}

animalitos/templates/detalle_producto.html
<h2>{{ producto.nombre }}</h2>
<p>Precio: {{ producto.precio }}</p>
<p>Descripción: {{ producto.descripcion }}</p>

animalitos/templates/donaciones.html
{% extends 'base.html' %}

{% block content %}
  <style>
    /* Estilos personalizados */
    .donaciones {
      text-align: center;
      margin-top: 50px;
    }
    .gallery {
      display: flex;
      justify-content: center;
      align-items: center;
      flex-wrap: wrap;
    }
    .gallery a {
      margin: 10px;
    }
    .gallery img {
      width: 200px;
      height: 200px;
      object-fit: cover;
    }
  </style>

  <section id="donaciones" class="py-md-5 donaciones">
    <h2>Donaciones</h2>
    <div class="gallery">
      <a href="http://www.santuarioteresadelosandes.cl/new/images/banners/Portada/7.jpg" data-fancybox="gallery" data-caption="Descripción de la imagen 1">
        <img src="https://fundacionhuellaanimal.cl/" alt="Imagen 1">
      </a>
      <a href="ruta-imagen-2.jpg" data-fancybox="gallery" data-caption="Descripción de la imagen 2">
        <img src="ruta-miniatura-2.jpg" alt="Imagen 2">
      </a>
      <!-- Agrega más imágenes aquí -->
    </div>
  </section>

  <script>
    $(document).ready(function() {
      // Inicializar Fancybox
      $('[data-fancybox="gallery"]').fancybox({
        loop: true, // Permitir bucle de la galería
        buttons: [
          "zoom",
          "slideShow",
          "fullScreen",
          "thumbs",
          "close"
        ] // Mostrar botones adicionales
      });
    });
  </script>
{% endblock %}

animalitos/templates/nosotros.html
<!-- nosotros.html -->
{% extends 'base.html' %} {% block content %}

<title>Nosotros</title>

<body font-family="Helvetica Neue sans-serif">
    <section id="nosotros" class="pt-md-5">
      <h2 class="text-center my-5">NOSOTROS</h2>
      <div class="container">
        <div class="row justify-content-center align-items-center gy-3">
          <div class="col-md-4">
            <div class="card">
              <img src="https://avatars.githubusercontent.com/u/100003286?v=4" class="card-img-top" alt="..." />
              <div class="card-body text-center">
                <h5 class="card-title">Felipe Álvarez</h5>
                <p class="card-text">Licenciado en Filosofía - UCH.</p>
                <p class="card-text">Analista Programador Computacional - Duoc UC.</p>
                <a href="https://github.com/DonFelipessss" class="btn btn-primary">LinkedIn</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section id="faq" class="py-md-5"></section>
  </body>

  <div class="container marketing">
    <!-- Cuerpo de Inicio -->

    <hr class="featurette-divider" />

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">
          Orientación<span class="text-body-secondary">
            Sin Fines de lucro.</span
          >
        </h2>
        <p class="lead">
          todo partió através de las redes sociales, pero en la actualidad es
          casi imposible dar abasto a la demanda através de las redes sociales.
          Por eso, alumnos del Duoc nos han ayudado a construir una aplicación
          web
        </p>
      </div>
      <div class="col-md-5">
        <img
          src="https://www.ust.cl/wp-content/uploads/sites/6/2016/03/medicina-veterinaria-716x400.jpg"
          class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto"
          width="500"
          height="500"
          role="img"
          aria-label="Placeholder: 500x500"
          preserveAspectRatio="xMidYMid slice"
          focusable="false"
          alt="Descripción de la imagen"
        />
      </div>
    </div>

    <hr class="featurette-divider" />

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading fw-normal lh-1">
          Artículos para mascotas:
          <span class="text-body-secondary">Desde gatos hasta aves</span>
        </h2>
        <p class="lead">
          Buscamos llegar a un amplio círculo de clientes con tal de generar la
          mayor cantidad de ingresos posibles
        </p>
      </div>
      <div class="col-md-5">
        <img
          src="https://assets.jumpseller.com/store/ohana-petshop/themes/245530/options/16281289/tienda-animales.jpg?1586041235"
          class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto"
          width="500"
          height="500"
          role="img"
          aria-label="Placeholder: 500x500"
          preserveAspectRatio="xMidYMid slice"
          focusable="false"
          alt="Descripción de la imagen"
        />
      </div>
    </div>

    <hr class="featurette-divider" />

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">
          Por último queremos agradecer
          <span class="text-body-secondary">A la institución Duoc Uc.</span>
        </h2>
        <p class="lead">
          Gracias a sus alumnos y a la calidad de sus profesores,este sitio ha
          podido ser construído de forma gratuita por nuestros colegas.
        </p>
      </div>
      <div class="col-md-5">
        <img
          src="https://seeklogo.com/images/D/duoc-uc-logo-F1437952BE-seeklogo.com.png"
          class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto"
          width="500"
          height="500"
          role="img"
          aria-label="Placeholder: 500x500"
          preserveAspectRatio="xMidYMid slice"
          focusable="false"
          alt="Descripción de la imagen"
        />
      </div>
    </div>

    <hr class="featurette-divider" />

    <!-- /fin -->
  </div>
  <!--Pie de página-->
  <footer class="container">
    <p class="float-end"><a href="#">Arriba</a></p>
    <p>© 2023 DUOC UC. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
    <p>Página realizada Por: <a href="#">Felipe Álvarez</a></p>
  </footer>

  {% endblock %}
</body>

animalitos/templates/subseccion.html
<h2>{{ subseccion.nombre }}</h2>
<ul>
  {% for producto in productos %}
    <li><a href="{% url 'animalitos:detalle_producto' producto.id %}">{{ producto.nombre }}</a></li>
  {% endfor %}
</ul>